#!/bin/bash
openapi-generator-cli generate -i https://test.decstream.very-soft.com/admin-api/v2/api-docs -g typescript-axios --additional-properties=enumPropertyNaming=UPPERCASE,withSeparateModelsAndApi=true,modelPackage=models,apiPackage=api,authMethods=false -o src/api --skip-validate-spec
