#!/bin/bash
openapi-generator-cli generate -i http://localhost:8080/v2/api-docs -g typescript-axios --additional-properties=enumPropertyNaming=UPPERCASE,withSeparateModelsAndApi=true,modelPackage=models,apiPackage=api,authMethods=false -o src/api --skip-validate-spec
