/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageDto
 */
export interface MessageDto {
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    roomId?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    updated?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageDto
     */
    userId?: string;
}


