/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MessageDto } from './message-dto';
import { Pageable } from './pageable';
import { Sort } from './sort';

/**
 * 
 * @export
 * @interface PageMessageDto
 */
export interface PageMessageDto {
    /**
     * 
     * @type {Array<MessageDto>}
     * @memberof PageMessageDto
     */
    content?: Array<MessageDto>;
    /**
     * 
     * @type {boolean}
     * @memberof PageMessageDto
     */
    empty?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageMessageDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageMessageDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageMessageDto
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMessageDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {Pageable}
     * @memberof PageMessageDto
     */
    pageable?: Pageable;
    /**
     * 
     * @type {number}
     * @memberof PageMessageDto
     */
    size?: number;
    /**
     * 
     * @type {Sort}
     * @memberof PageMessageDto
     */
    sort?: Sort;
    /**
     * 
     * @type {number}
     * @memberof PageMessageDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMessageDto
     */
    totalPages?: number;
}


