/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    status?: UserDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    updated?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    userAppRole?: UserDtoUserAppRoleEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UserDtoStatusEnum {
    ACTIVE = 'ACTIVE',
    GLOBAL_BLOCKED = 'GLOBAL_BLOCKED'
}
/**
    * @export
    * @enum {string}
    */
export enum UserDtoUserAppRoleEnum {
    ADMIN = 'ADMIN',
    CLIENT = 'CLIENT'
}



